"""add welding_gas_psi_end column

Revision ID: 65ed2a99d791
Revises: 61167fdff2f5
Create Date: 2026-03-10 14:35:52.623675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ed2a99d791'
down_revision: Union[str, None] = '61167fdff2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_history', sa.Column('welding_gas_psi_end', sa.Float(), nullable=True))
    op.add_column('reservations', sa.Column('welding_gas_psi_end', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'welding_gas_psi_end')
    op.drop_column('reservation_history', 'welding_gas_psi_end')
    # ### end Alembic commands ###
